backend:
  name: github
  repo: dany921/studiocutrulla
  branch: main

media_folder: "public/lovable-uploads"
public_folder: "/lovable-uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/data/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Immagine", name: "image", widget: "image" }
      - { label: "Testo", name: "body", widget: "markdown" }
