backend:
  name: git-gateway
  branch: main # o master, a seconda del tuo repository

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data di pubblicazione", name: "date", widget: "datetime"}
      - {label: "Descrizione", name: "description", widget: "text"}
      - {label: "Contenuto", name: "body", widget: "markdown"}